# Generated by Django 4.2.6 on 2023-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_quiz_title_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
