# Generated by Django 4.2.6 on 2023-11-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_quiz_description_quiz_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quizgroup'),
        ),
    ]
