# Generated by Django 4.2.6 on 2023-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_quiz_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(default='single-choice', max_length=14),
        ),
    ]
