# Generated by Django 4.2.6 on 2023-11-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('TY', 'Typing'), ('SC', 'Single Choice'), ('MC', 'Multi Choice')], default='SC', max_length=2),
        ),
    ]
