# Generated by Django 4.2.6 on 2023-11-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0009_answers_correct_questionresult_result_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
