# Generated by Django 4.2.6 on 2023-11-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0011_remove_quiz_quiz_type_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
