# Generated by Django 4.2.6 on 2023-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0012_remove_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TY', 'Typing'), ('SC', 'Single Choice'), ('MC', 'Multi Choice')], default='SC', max_length=2, null=True),
        ),
    ]
