# Generated by Django 4.2.6 on 2023-11-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0013_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TY', 'Typing'), ('SC', 'Single Choice'), ('MC', 'Multi Choice')], default='TY', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.user'),
        ),
    ]
