# Generated by Django 4.2.6 on 2023-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0014_alter_question_type_alter_questionresult_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_points',
            field=models.IntegerField(default=10),
        ),
    ]
