# Generated by Django 4.2.6 on 2023-11-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0015_remove_quizresult_time_quiz_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.user'),
        ),
    ]
