# Generated by Django 4.2.6 on 2023-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0016_alter_quizresult_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgroup',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
