# Generated by Django 4.2.6 on 2023-12-13 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0018_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(6, 'the password must be at least 6 characters long')]),
        ),
    ]
