# Generated by Django 4.2.1 on 2024-02-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0020_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='point',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
