# Generated by Django 4.2.1 on 2024-02-15 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0021_answer_point_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 15, 9, 32, 174882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
