# Generated by Django 4.2.1 on 2024-02-15 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0022_quizresult_date_time_alter_answer_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 15, 11, 9, 338871, tzinfo=datetime.timezone.utc)),
        ),
    ]
