# Generated by Django 4.2.1 on 2024-02-27 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0024_questionresult_quiz_result_id_alter_question_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 13, 44, 59, 518327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AnswerResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_choice', models.BooleanField()),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.answer')),
                ('quiz_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quizresult')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
