# Generated by Django 4.2.1 on 2024-02-29 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0025_alter_quizresult_date_time_answerresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerresult',
            name='user_choice',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 12, 42, 20, 953359, tzinfo=datetime.timezone.utc)),
        ),
    ]
