# Generated by Django 4.2.1 on 2024-03-25 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0027_remove_quiz_group_id_quiz_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='groups',
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='quizzes',
            field=models.ManyToManyField(related_name='quizgroup', to='QuizApp.quiz'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 14, 26, 53, 518443, tzinfo=datetime.timezone.utc)),
        ),
    ]
